### PR TITLE
Lint the JS to have a semi-consistent, correct style

### PR DESCRIPTION
**Pull request by janxious**
Tests pass, probably fine!

### CODE REVIEW

**Comment by janxious** [comment]
```
$ eslint ./*.js lib/*.js test/*.js

/Users/joel/projects/instrumental-node/index.js
  1:1  error  'use strict' is unnecessary inside of modules  strict

/Users/joel/projects/instrumental-node/lib/instrumental.js
  1:1  error  'use strict' is unnecessary inside of modules  strict

/Users/joel/projects/instrumental-node/test/intrumental-test.js
   1:1   error    'use strict' is unnecessary inside of modules  strict
  10:14  warning  Missing function expression name               func-names
  11:13  warning  Missing function expression name               func-names
  13:43  warning  Missing function expression name               func-names
  41:47  warning  Missing function expression name               func-names
  79:44  warning  Missing function expression name               func-names

✖ 8 problems (3 errors, 5 warnings)
```

Honestly not sure what to do with those, so ¯\\\_(ツ)\_/¯

**Comment by jqr** [comment]
:+1:

**Comment by jqr** [comment]
For future verification, what was the command you used to lint?

**Comment by janxious** [comment]
I mean, I can just add all the stuff to the project. The command I used is above in the console output, and the lintrc is:

```
$ cat .eslintrc.json
{
  "extends": "airbnb",
  "plugins": [
    "react"
  ],
  "rules" : {
    "no-console": 0,
    "no-unused-vars": 0,
    "no-param-reassign" : 0,
    "valid-jsdoc": 0,
    "spaced-comment": 0,
    "key-spacing": 0,
    "padded-blocks": 0,
    "no-undef": 0,
    "comma-dangle": [1, "always-multiline"],
    "no-multi-spaces": 0,
    "max-len": 0,
    "prefer-template": 0,
    "no-eval": 0,
    "curly": 0
  }
}
```

**Comment by janxious** [comment]
Merging, and we can talk about adding linting automagically or as part of the merge process or something.

**Pull request merged**
